targetDatabase: "postgres://test:test@test:5432/test"

sourceDatabase: "postgres://test:test@test:5432/testsource"

tables:
  - name: TextTemplates
    columns:
      - Id
      - LanguageId
      - Text
      - TextHeader
      - Format
    primaryKeys:
      - Id
      - LanguageId
    onlyWhere:
      - name: LanguageId
        value: ''
        type: string
  - name: LanguageItems
    columns:
      - LanguageId
      - LanguageKey
      - LanguageValue
      - LanguageItemType
    primaryKeys:
      - LanguageId
      - LanguageKey