
targetDatabase: "postgres://test:tea@sadfaasdf:5432/db?schema=asdf"


sourceDatabase: "postgres://test:tea@sadfaasdf:5432/dbsource?schema=asdf"

tables:
  - name: EquipmentOperatingUnits
    columns:
      - Id
      - Name
      - Archived
      - Description
    primaryKeys:
      - Id

  - name: EquipmentCategories
    columns:
      - Id
      - Name
      - Archived
      - Description
      - IsSelectableCategory
      - ParentEquipmentCategoryId
    primaryKeys:
      - Id
    onlyWhere:
      - name: Id
        type: int
        value: 1
    noDelete: true # Deactivate delete for this table