name: Pack
on:
  push:
    tags:
      - 'v*.*.*'
      - 'v*.*.*-**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - run: go test ./...
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: actions/setup-go@v1
        with:
          go-version: 1.18
      - name: Run Tests
        run: go test ./... -cover
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
