name: Pack
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'

      - run: make test
        name: Run go test, lint and scan for vulnerabilities

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  gcr:
    name: Push to GCR as a Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.21'

      - uses: imjasonh/setup-ko@v0.6

      - run: ko build ./cmd/stage-sync -B
