name: Pack
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'

      - run: make test
        name: Run go test, lint and scan for vulnerabilities

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20'
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
