name: Test
on:
  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    name: coverage
    steps:
      - uses: actions/checkout@v3
          
      - name: Code Climate Coverage Action
        run: |
          make test-ci
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}